### ISSUE TITLE
Classes with Same name and Different Packages are being triggered JCASC

### ISSUE THREAD

**Issue by timja** [jenkinsci/windows-azure-storage-plugin#177]
<p>When using Azure Credentials with CASC references to Azure Credentials ( plugin azure-credentials:1.6.1 ) get caught by a different package</p>

<p>Example for CASC confs</p>

<p> </p>
<ul class="alternate" type="square">
	<li><div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">azure:
 clientId: <span class="code-quote">"${azure_clientId}"</span>
 clientSecret: <span class="code-quote">"${azure_clientSecret}"</span>
 description: <span class="code-quote">"Azure Credentials"</span>
 id: <span class="code-quote">"X"</span>
 scope: GLOBAL
 subscriptionId: <span class="code-quote">"${azure_subscriptionId}"</span>
 azureEnvironmentName: <span class="code-quote">"Azure"</span></pre>
</div></div></li>
</ul>

<p>This results in:</p>

<p>```</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">jenkins_1 | io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements <span class="code-keyword">for</span> type <span class="code-keyword">class </span>com.microsoftopentechnologies.windowsazurestorage.helper.AzureCredentials : azureEnvironmentName,clientId,clientSecret,subscriptionId,tenant.
 jenkins_1 | Available attributes : blobEndpointURL, description, id, scope, storageAccountName, storageKey
 jenkins_1 | at io.jenkins.plugins.casc.BaseConfigurator.handleUnknown(BaseConfigurator.java:378)
 jenkins_1 | at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:367)
 jenkins_1 | at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:277)
 jenkins_1 | at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.configure(DataBoundConfigurator.java:83)
 jenkins_1 | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$doConfigure$16668e2$1(HeteroDescribableConfigurator.java:278)
 jenkins_1 | at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:201)
 jenkins_1 | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.doConfigure(HeteroDescribableConfigurator.java:278)
 jenkins_1 | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$<span class="code-keyword">null</span>$2(HeteroDescribableConfigurator.java:86)
 jenkins_1 | at io.vavr.control.Option.map(Option.java:373)
 jenkins_1 | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:86)
 jenkins_1 | at io.vavr.Tuple2.apply(Tuple2.java:239)
 jenkins_1 | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
 jenkins_1 | at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:55)
 jenkins_1 | at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.tryConstructor(DataBoundConfigurator.java:153)
 jenkins_1 | at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.instance(DataBoundConfigurator.java:77)
 jenkins_1 | at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:268)
 jenkins_1 | at io.jenkins.plugins.casc.impl.configurators.DataBoundConfigurator.check(DataBoundConfigurator.java:101)
 jenkins_1 | at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:345)
 jenkins_1 | at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)
 jenkins_1 | at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:353)
 jenkins_1 | at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:288)
 jenkins_1 | at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$6(ConfigurationAsCode.java:684)
 jenkins_1 | at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:646)
 jenkins_1 | Caused: io.jenkins.plugins.casc.ConfiguratorException: credentials: error configuring <span class="code-quote">'credentials'</span> with <span class="code-keyword">class </span>com.cloudbees.plugins.credentials.casc.CredentialsRootConfigurator configurator
 jenkins_1 | at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:652)
 jenkins_1 | at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:684)
 jenkins_1 | at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:668)
 jenkins_1 | at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:567)
 jenkins_1 | at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:280)
 jenkins_1 | at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:272)
 jenkins_1 | Caused: java.lang.reflect.InvocationTargetException
 jenkins_1 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 jenkins_1 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 jenkins_1 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 jenkins_1 | at java.lang.reflect.Method.invoke(Method.java:498)
 jenkins_1 | at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
 jenkins_1 | Caused: java.lang.Error
 jenkins_1 | at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
 jenkins_1 | at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
 jenkins_1 | at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
 jenkins_1 | at jenkins.model.Jenkins$5.runTask(Jenkins.java:1118)
 jenkins_1 | at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
 jenkins_1 | at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
 jenkins_1 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 jenkins_1 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 jenkins_1 | at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:748)</pre>
</div></div>
<p>```</p>

<p>The same is valid if we set *<b>Azure Storage Credentials</b>*</p>

<p>```</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"> - azureStorageAccount:
    blobEndpointURL: <span class="code-quote">"https:<span class="code-comment">//blob.core.windows.net/"</span>
</span>    id: <span class="code-quote">"X-Storage"</span>
    scope: GLOBAL
    storageAccountName: <span class="code-quote">"${azure_storageAccountName}"</span>
    storageKey: <span class="code-quote">"${azure_storageKey}"</span> azure:
    
- azure:
   id: <span class="code-quote">"X"</span>
   scope: GLOBAL
   subscriptionId: <span class="code-quote">"${azure_subscriptionId}"</span>
   azureEnvironmentName: <span class="code-quote">"Azure"</span> 
   clientId: <span class="code-quote">"${azure_clientId}"</span>
   clientSecret: <span class="code-quote">"${azure_clientSecret}"</span>
   description: <span class="code-quote">"Azure Credentials"</span></pre>
</div></div>
<p> </p>

<p>```</p>

<p>The values for azureStorageAccount have been exported from CASC to check if setting it would not trigger this bug.</p>

<p>The above results in triggering twice the Same StackTrace as set above.</p>

<p>Notice the package used:<br/>
 *<b>com.microsoftopentechnologies.windowsazurestorage.helper.AzureCredentials</b>*</p>

<p>It should in fact call the one below:<br/>
 *<b>com.microsoft.azure.util.AzureCredentials</b>*</p>

<p>An issue was created at JCASC github: <a href="https://github.com/jenkinsci/configuration-as-code-plugin/issues/963" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/configuration-as-code-plugin/issues/963</a></p>

<p>However, from comments in the issue referenced above, the problem lies on how both Azure-Credentials and windows-azure-storage reference the same class on different packages.</p>
<i>[JENKINS-58710] created by ilhicas</i>

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/windows-azure-storage-plugin/pull/160
