### ISSUE TITLE
Download from azure archive missing

### ISSUE THREAD

**Issue by park896** [jenkinsci/windows-azure-storage-plugin#34]
The download from azure archive build step option is not available with the most recent version. I believe it has something to do with this error that appears in the jenkins log.

> Failed to instantiate Key[type=com.microsoftopentechnologies.windowsazurestorage.AzureStorageBuilder$AzureStorageBuilderDesc, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Unable to provision, see the following errors:

>
    1) Error injecting constructor, java.lang.NoClassDefFoundError: hudson/plugins/copyartifact/BuildSelector

>
    at com.microsoftopentechnologies.windowsazurestorage.AzureStorageBuilder$AzureStorageBuilderDesc.<init>(AzureStorageBuilder.java:295)
    1 error
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:52)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
        at hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1.get(ExtensionFinder.java:424)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
        at hudson.ExtensionFinder$GuiceFinder._find(ExtensionFinder.java:386)
        at hudson.ExtensionFinder$GuiceFinder.find(ExtensionFinder.java:377)
        at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:472)
        at hudson.ExtensionList.load(ExtensionList.java:365)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
        at hudson.ExtensionList.getComponents(ExtensionList.java:168)
        at hudson.DescriptorExtensionList.load(DescriptorExtensionList.java:191)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:303)
        at hudson.ExtensionList.iterator(ExtensionList.java:157)
        at org.jenkinsci.plugins.xunit.AliasInitializer.addAliases(AliasInitializer.java:47)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:1066)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
    Caused by: java.lang.NoClassDefFoundError: hudson/plugins/copyartifact/BuildSelector
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at hudson.model.Descriptor.<init>(Descriptor.java:288)
        at hudson.tasks.BuildStepDescriptor.<init>(BuildStepDescriptor.java:56)
        at com.microsoftopentechnologies.windowsazurestorage.AzureStorageBuilder$AzureStorageBuilderDesc.<init>(AzureStorageBuilder.java:295)
        at com.microsoftopentechnologies.windowsazurestorage.AzureStorageBuilder$AzureStorageBuilderDesc$$FastClassByGuice$$54a06dd3.newInstance(<generated>)
        at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
        at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        ... 29 more
    Caused by: java.lang.ClassNotFoundException: hudson.plugins.copyartifact.BuildSelector
        at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1373)
        at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
        at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
        at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by clguimanMSFT** [comment]
Do you mean "Download from Azure Blob Storage" step?
If so, can you please check that you have the copy artifact plugin installed?

**Comment by park896** [comment]
That is indeed what I meant and you were correct about the problem as well. I didn't realize the Download step had a dependency on that other plugin.

**Comment by clguimanMSFT** [comment]
That's odd. The dependency is declared: https://wiki.jenkins-ci.org/display/JENKINS/Windows+Azure+Storage+Plugin
I guess Jenkins should make sure that the plugin is installed

**Comment by robmccready** [comment]
It looks like the copyartifacts plugin is marked as an optional dependency. That might make sense if the download functionality is considered secondary to upload. The docs should be updated to reflect that download support requires the copyartifacts dependency to also be installed.
