### ISSUE TITLE
azureUpload doesn't provide usefull debug information

### ISSUE THREAD

**Issue by clguimanMSFT** [jenkinsci/windows-azure-storage-plugin#59]
I tried to use the azureUpload command for our CI, but I couldn't figure out what I set wrong. There's no usefull debug information.
Here's the groovy script: https://github.com/azure-devops/ci/commit/90d098730e478a5037e8f89950e891edb1e29292
And here's the error:
http://devops-ci.westcentralus.cloudapp.azure.com/job/azure-credentials/job/jenkinsci/job/master/44/console

MicrosoftAzureStorage - Uploading files to Microsoft Azure
MicrosoftAzureStorage - Failed to upload any build artifacts to Azure Storage 
Verify the list of files to upload and that the Ant glob syntax is correct
ERROR: MicrosoftAzureStorage - Error occurred while uploading to Azure - devopspublicstorage
java.io.IOException: MicrosoftAzureStorage - Failed to upload any build artifacts to Azure Storage 
Verify the list of files to upload and that the Ant glob syntax is correct
	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:420)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:78)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:65)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

The plugin should provide better logs.

**Comment by ArchangelSDY** [comment]
It seems no files matching the name pattern can be found. I've created a PR to print more logs and improved the error message.
