### ISSUE TITLE
Failing with Azure Stack

### ISSUE THREAD

**Issue by charliejllewellyn** [jenkinsci/windows-azure-storage-plugin#93]
Hi I am trying to use this with Azure Stack. It is failing with:

```
Failed to validate storage account details. Please verify storage account name and key. If you are using a private or other Windows Azure cloud service, make sure that the blob endpoint url is correct.
Storage Account name --->jenkinsupload<----
Blob end point url --->https://jenkinsupload.blob.local.azurestack.external/<----
ERROR: Step ‘Upload artifacts to Microsoft Azure Storage’ aborted due to exception: 
java.io.IOException: Plugin can not continue, until previous errors are addressed
	at com.microsoftopentechnologies.windowsazurestorage.WAStoragePublisher.perform(WAStoragePublisher.java:403)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
```

This could be for many reasons, SSL verification (although I have added the root cert to the java keystore), incorrect API versions, or incorrect resource provided in the token request. 

How can I enable debug logging and where should I look to troubleshoot this please.

**Comment by juniwang** [comment]
Unfortunately we haven't tested the plugin in Azure Stack nor exposed the underlying exception. Might be better to verbose the underlying exception for debuging in next release.  

For now, it's really hard to find the root cause.  But at my first sight, your blob endpoint Url https://jenkinsupload.blob.local.azurestack.external/ is beyond our expect. See https://github.com/jenkinsci/windows-azure-storage-plugin/blob/dev/src/main/java/com/microsoftopentechnologies/windowsazurestorage/helper/AzureUtils.java#L199. We tried to parse the endpoint suffix by finding substring `core` in the url. That means in your case, you didn't even try to connect to your AzureStack.

If it's possible, could you please try to build and debug the plugin on your side? Sure we can do some fixes about logs/endpoints but it's hard for us to validate it since we don't have a AzureStack instance.

**Comment by gavinfish** [comment]
Moved to jira https://issues.jenkins-ci.org/browse/JENKINS-55633.
